### ISSUE TITLE
Disabling strict qualifier

### ISSUE THREAD

**Issue by eredzik** [trevyn/turbosql#25]
Is it possible to disable strict qualifier? Many tools dont support it and crash when trying to open database

**Comment by trevyn** [comment]
This is a reasonable request! I just added a `sqlite-compat-no-strict-tables` feature to allow this, and cut a new 0.6 release. So change your dep to:

```toml
turbosql = {version = "0.6", features = ["sqlite-compat-no-strict-tables"]}
```

and then delete your `migrations.toml` file and you should be good to go. Let me know if you run into any issues!
